"""users table

Revision ID: 53c2b7368832
Revises: 
Create Date: 2022-05-19 17:20:05.578243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c2b7368832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('tweets_trump', 'tweetBody',
               existing_type=sa.NUMERIC(precision=280),
               nullable=True)
    op.alter_column('tweets_trump', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tweets_trump', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tweets_trump', 'retweets',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets_trump', 'retweets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tweets_trump', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tweets_trump', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tweets_trump', 'tweetBody',
               existing_type=sa.NUMERIC(precision=280),
               nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
